export const LANGUAGE_MAP: any = {
  "plaintext": [".txt"],
  "abap": [".abap"],
  "apex": [".cls"],
  "azcli": [".azcli"],
  "bat": [".bat", ".cmd"],
  "bicep": [".bicep"],
  "cameligo": [".mligo"],
  "clojure": [".clj", ".cljs", ".cljc", ".edn"],
  "coffeescript": [".coffee"],
  "c": [".c", ".h"],
  "cpp": [".cpp", ".cc", ".cxx", ".hpp", ".hh", ".hxx"],
  "csharp": [".cs", ".csx", ".cake"],
  "csp": [],
  "css": [".css"],
  "cypher": [".cypher", ".cyp"],
  "dart": [".dart"],
  "dockerfile": [".dockerfile"],
  "ecl": [".ecl"],
  "elixir": [".ex", ".exs"],
  "flow9": [".flow"],
  "fsharp": [".fs", ".fsi", ".ml", ".mli", ".fsx", ".fsscript"],
  "freemarker2": [".ftl", ".ftlh", ".ftlx"],
  "go": [".go"],
  "graphql": [".graphql", ".gql"],
  "handlebars": [".handlebars", ".hbs"],
  "hcl": [".tf", ".tfvars", ".hcl"],
  "html": [
    ".html",
    ".htm",
    ".shtml",
    ".xhtml",
    ".mdoc",
    ".jsp",
    ".asp",
    ".aspx",
    ".jshtm"
  ],
  "ini": [".ini", ".properties", ".gitconfig"],
  "java": [".java", ".jav"],
  "javascript": [".js", ".es6", ".jsx", ".mjs", ".cjs"],
  "julia": [".jl"],
  "kotlin": [".kt", ".kts"],
  "less": [".less"],
  "lexon": [".lex"],
  "lua": [".lua"],
  "liquid": [".liquid", ".html.liquid"],
  "m3": [".m3", ".i3", ".mg", ".ig"],
  "markdown": [
    ".md",
    ".markdown",
    ".mdown",
    ".mkdn",
    ".mkd",
    ".mdwn",
    ".mdtxt",
    ".mdtext"
  ],
  "mdx": [".mdx"],
  "mips": [".s"],
  "msdax": [".dax", ".msdax"],
  "mysql": [],
  "objective-c": [".m"],
  "pascal": [".pas", ".p", ".pp"],
  "pascaligo": [".ligo"],
  "perl": [".pl", ".pm"],
  "pgsql": [],
  "php": [".php", ".php4", ".php5", ".phtml", ".ctp"],
  "pla": [".pla"],
  "postiats": [".dats", ".sats", ".hats"],
  "powerquery": [".pq", ".pqm"],
  "powershell": [".ps1", ".psm1", ".psd1"],
  "proto": [".proto"],
  "pug": [".jade", ".pug"],
  "python": [".py", ".rpy", ".pyw", ".cpy", ".gyp", ".gypi"],
  "qsharp": [".qs"],
  "r": [".r", ".rhistory", ".rmd", ".rprofile", ".rt"],
  "razor": [".cshtml"],
  "redis": [".redis"],
  "redshift": [],
  "restructuredtext": [".rst"],
  "ruby": [".rb", ".rbx", ".rjs", ".gemspec", ".pp"],
  "rust": [".rs", ".rlib"],
  "sb": [".sb"],
  "scala": [".scala", ".sc", ".sbt"],
  "scheme": [".scm", ".ss", ".sch", ".rkt"],
  "scss": [".scss"],
  "shell": [".sh", ".bash"],
  "sol": [".sol"],
  "aes": [".aes"],
  "sparql": [".rq"],
  "sql": [".sql"],
  "st": [
    ".st",
    ".iecst",
    ".iecplc",
    ".lc3lib",
    ".TcPOU",
    ".TcDUT",
    ".TcGVL",
    ".TcIO"
  ],
  "swift": [".swift"],
  "systemverilog": [".sv", ".svh"],
  "verilog": [".v", ".vh"],
  "tcl": [".tcl"],
  "twig": [".twig"],
  "typescript": [".ts", ".tsx", ".cts", ".mts"],
  "vb": [".vb"],
  "wgsl": [".wgsl"],
  "xml": [
    ".xml",
    ".xsd",
    ".dtd",
    ".ascx",
    ".csproj",
    ".config",
    ".props",
    ".targets",
    ".wxi",
    ".wxl",
    ".wxs",
    ".xaml",
    ".svg",
    ".svgz",
    ".opf",
    ".xslt",
    ".xsl"
  ],
  "yaml": [".yaml", ".yml"],
  "json": [
    ".json",
    ".bowerrc",
    ".jshintrc",
    ".jscsrc",
    ".eslintrc",
    ".babelrc",
    ".har"
  ]
}
